name: yahoo_finance
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Cupertino Icons
  cupertino_icons: ^1.0.2

  # used to make code more functional (especially use of "Either")
  dartz: ^0.10.1

  # http client
  http: ^0.13.4

  # dependency injection and feature modularization
  flutter_modular: ^4.5.0

  # state and business rule management (Cubit)
  flutter_bloc: ^8.0.1

  # local persistence
  shared_preferences: ^2.0.13

  # localization facilities like convert date formats
  intl: ^0.17.0

  # for validating email addresses
  email_validator: ^2.0.1

  # being able to compare objects in Dart
  equatable: ^2.0.3

  # being able use SVG to show images
  flutter_svg: ^1.0.3

  # handling of loading images from the internet
  cached_network_image: ^3.2.0

  # visual effect on card loading
  shimmer: ^2.0.0


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  # code generator
  build_runner: ^2.1.7
  # test lib
  mockito: ^5.0.16
  # use to emule modular injections
  modular_test: ^1.0.1+1
  # use to test cubits
  bloc_test: ^9.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: AsapCondensed
      fonts:
        - asset: assets/fonts/AsapCondensed-Bold.ttf
        - asset: assets/fonts/AsapCondensed-Regular.ttf
